spring.application.name=pay
<<<<<<< HEAD
=======
<<<<<<< HEAD
# DB 설정
spring.datasource.driver-class-name=${secrets.DRIVER_CLASS_NAME}
spring.datasource.url=${secrets.URL}
spring.datasource.username=${secrets.USERNAME}
spring.datasource.password=${secrets.PASSWORD}

# JPA 설정
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=none

server.port=9000
=======
>>>>>>> ea0d57a2ae2d2540866efcadfd6e85463f010eda
>>>>>>> master
